# Generated by Django 2.0.3 on 2022-10-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0007_auto_20180311_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='has_herd',
            field=models.BooleanField(default=False, help_text='If enabled, will show herd field while adding/updating animals.', verbose_name='show herd field'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='has_weight',
            field=models.BooleanField(default=False, help_text='If enabled, will show weight field while adding/updating animals.', verbose_name='show weight field'),
        ),
    ]
